[build]
  publish = "./"

[[redirects]]
  from = "http://www.canberead.com/*"
  to = "http://read.machinepresence.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://www.canberead.com/*"
  to = "https://read.machinepresence.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "http://canberead.com/*"
  to = "http://read.machinepresence.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://canberead.com/*"
  to = "https://read.machinepresence.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
